### PR TITLE
Setup colors and approach to customizing mui components

### PR DESCRIPTION
**Pull request by nicolauscg**
Setup color hexes used in `colors.ts` then applies default styling customization with mui's theme, an example in this PR is `<Chip />` component, others using it will directly have matching appearance to prototype, a downside is that tailwind cannot be used as mui theme involves css properties not classnames and that the theme customization will get large later on.

An alternative is to create our own `<CustomChip />` component that modifies mui's `<Chip />` styling to our needs, but this makes devs have to look if we already have a custom component. With us trying to match the prototype, I dont think we will ever need the vanila `<Chip />` styling, so Im leaning towards using mui theme.

For something that we already have as a component e.g. NavBar, styling customization can be applied there directly.

todo

- [x] fix positioning of chips in waiting room

### CODE REVIEW

**Comment by nicolauscg** [comment]
Opinions on approach in PR description is welcome @daystram @wahyuadt

**Comment by wahyuadt** [comment]
So the only external styling is the color?

**Comment by daystram** [comment]
Looks good to me

**Comment by nicolauscg** [comment]
> So the only external styling is the color?

yeah, see snippet below for why I didn't put it inside theme

```
palette: {
  // I tried to put it in the theme directly like
  primary: {
    light: "#someHex",
  },
},
overrides: {
  MuiChip: {
    colorPrimary: {
      // but dont think theres a way to refer to primary.light from here
      backgroundColor: ...,
    },
  },
},
```

**Comment by nicolauscg** [comment]
to add to argument for theme vs custom components, just thought of them now

- custom components allow adding logic through states, useEffects, etc
- color styling in mui is limited to primary and secondary, the approach for the Chip component is to also incorporate variant e.g. from pic below, from left to right, Chip is of type: color primary only, color secondary only, color primary and variant outlined.

image

so yeah we could agree to go for theme customization first and if it does the job then good, else we could create a component

mui talks about this on approaches number 3 and 5 here https://material-ui.com/customization/components/#3-specific-variation-of-a-component

**Review by daystram — APPROVED** [review]

**Pull request merged**
