### PR TITLE
[FAB-107] HiFi Clasroom

### PR DESCRIPTION
**Pull request by daystram**
- [x] editable cards
- [x] start/stop session on cards
- [x] bug: reset editing form after cancel
- [x] bug: remove card after deletion

### CODE REVIEW

**Comment by daystram** [comment]
Is pretty much completed. @nicolauscg can u help figure out why the editing form field does not reset after cancellation? And what's the better approach to remove the deleted card?

**Comment by daystram** [comment]
Deletion issue was solved by using a mock state to retrigger render.

> Is pretty much completed. @nicolauscg can u help figure out why the editing form field does not reset after cancellation? And what's the better approach to remove the deleted card?

**Review by nicolauscg — COMMENTED** [review]
nice dialogs for confirming destructive actions, changes and the page appearance looks good other than points listed below

- found a bug if u edit classroom titled A to be B, save, then edit to C, but cancel, if u try to edit again, field will show A instead of C
- do we want to make the plus button more noticable? like adding a white background or smth, seems hard to notice

**Comment by daystram** [comment]
Solved both.

> nice dialogs for confirming destructive actions, changes and the page appearance looks good other than points listed below
> 
> * found a bug if u edit classroom titled A to be B, save, then edit to C, but cancel, if u try to edit again, field will show A instead of C
> * do we want to make the plus button more noticable? like adding a white background or smth, seems hard to notice

**Review by wahyuadt — APPROVED** [review]

**Pull request merged**
