### PR TITLE
[FAB-84] Hifi controller draw canvas

### PR DESCRIPTION
**Pull request by nicolauscg**
includes changes to match canvas related pages to hifi prototype.

### implementation details to note

- since eraser is a color, when switching from it to e.g. paint or fill tool, color will auto change to most recent non-eraser color
- canvas ref in Canvas component is changed to include callback for undo and record audio in addition to `HTMLCanvasElement` by using `useImperativeHandle()` hook so that CanvasToolbar component can do those two without moving too much logic from Canvas upwards to container
- includes Danny's cursor lag fix #44 

### bugs

- [x] after student record audio, clicking text does nothing, probably because tool mode is still audio
  - solved by showing that audio is currently selected tool, student must click text tool first if want to interact with them
- [x] cursor screen and canvas not centered even though its dimension is correct on chrome android mobile
  - fixed by playing around css grid
- [x] toolbar height on short screens exceeds viewport height
  - fixed by making it scroll on overflow

### out of scope

- make canvas drawing scaling dynamic so that resizing screen allows student to draw without any issue (no translation error)
- upon joining a started session on mobile with landscape orientation, canvas is not contained within the screen, leading to a scrollable page, however, changing orientation to potrait then to landscape again leads to the intended behavior, that is canvas is contained, note that without fix of previous point, drawing will not perfectly work

-------

todo list for personal use

Canvas component

- [x] do not show list of audio HTML elements on Canvas component as we consider only 1 most recent audio (had a discussion with Danny). In hub autoplay an audio on receive. This way, do not need UI for student to remove audio recording

CanvasToolbar component

- [x] add UI to adjust tool width, currently there is no way to change it
- [x] show currently selected color
- [x] think about better UI e.g. tooltip for recording audio, currently clickin on icon starts recording, clicking again stops it

about width of Canvas maintaining aspect ratio and being contained to screen

- [x] to make toolbar height same as canvas, extract logic to calculate canvas width upwards to container, may consider using `useContainRatio` hook
- [x] look for better way than hardcoding height as `100vh - 84px`, 84px is height of canvas + padding below it
- (changed to out of scope) after width of canvas DOM element is dynamic, attempt to make canvas drawing scaling dynamic, that is, resizing screen allows drawing without issue (no translation error)

hub, controller or story detail page related

- [x] add white background behind last canvas layer, must do in a level above Canvas component, keep in mind story detail page will display transparent canvas above an HTML image element
- [x] tidy up UI above canvas in Hub page to match style in controller page
- [x] keep row of chips in controller page one row regardless of screen size
- [x] consider extracting the layout structure to display canvas in full screen to a component as it is replicated across 3 areas: hub, controller and story detail

### CODE REVIEW

**Comment by nicolauscg** [comment]
for reviewer consideration, I noticed 

- audio is not recorded directly after pressing audio tool (which runs `recordAudio` callback), if this is worth looking into, can either add a delay in UI changing from mic icon to stop icon, or investigate whats causing the delay
- when holding left click and moving from outside to inside of canvas, it does not draw a line, a workaround for drawing lines to edges is to start from the center of canvas towards the edge, cannot do the other way around

**Comment by daystram** [comment]
holding left-click and moving the cursor into the canvas is intentionally made to not draw anything. this is an intended behaviour

**Comment by daystram** [comment]
Should we move the tool icon components to canvas/ ?

**Comment by nicolauscg** [comment]
Found some problems when I test it on chrome mobile, currently looking into it

- cursor screen not centered even though its dimension is correct
- toolbar height on short screens like my phone exceeds viewport height, will probably make it overflow scroll

**Comment by daystram** [comment]
I did not notice any delay between pressing the record button and starting the audio recording

**Comment by nicolauscg** [comment]
> I did not notice any delay between pressing the record button and starting the audio recording

okay then we can ignore it, probably specific to my machine then

**Comment by nicolauscg** [comment]
> Found some problems when I test it on chrome mobile, currently looking into it
> 
> * cursor screen and canvas not centered even though its dimension is correct, only white background is correctly centered
> * toolbar height on short screens like my phone exceeds viewport height, will probably make it overflow scroll

First is completely fixed. 

For the second one, toolbar is now scrollable if y-axis overflows, but there is still a smaller problem, read 2nd point in out of scope section of PR description for details.

**Review by daystram — APPROVED** [review]

**Pull request merged**
