### PR TITLE
[FAB-10] Canvas eraser

### PR DESCRIPTION
**Pull request by daystram**

### CODE REVIEW

**Review by nicolauscg — COMMENTED** [review]
changes looks fine, are we planning to keep eraser on colour section, which allows erase fill?

I tried an erase fill on a coloured line and looks like the edges are not cleanly erased, probably related to antialiasing

**Comment by nicolauscg** [comment]
> changes looks fine, are we planning to keep eraser on colour section, which allows erase fill?
> 
> I tried an erase fill on a coloured line and looks like the edges are not cleanly erased, probably related to antialiasing

decision for eraser to be a tool or colour deferred to later (UI/UX)
antialiasing stuff cannot be solved easily

**Review by nicolauscg — APPROVED** [review]
good

**Comment by daystram** [comment]
👽

**Pull request merged**
