### PR TITLE
[FAB-101] Achievement progress, page, notification, 🎉 

### PR DESCRIPTION
**Pull request by daystram**
- [x] Achievement progress
- [x] Achievement list page
- [x] Achievement notification
- [x] 🎊

### CODE REVIEW

**Comment by daystram** [comment]
a known bug but expected behaviour: when a student leaves and rejoins, the achievement progress for that user appears to reset

**Comment by daystram** [comment]
> a known bug but expected behaviour: when a student leaves and rejoins, the achievement progress for that user appears to reset

found the source. when the user rejoins, they will begin the text id back from 0, hence the text counter in useAchievement hook is not updated. not a bug

**Review by nicolauscg — COMMENTED** [review]
Changes are fine. 

About ur comment, `textId` is reset to 1 on every page, so if u are halfway through, placed x/10 text elements lets say, going to the next page will resume progress after placing x texts. Looking at git blame, that behavior was related to fixing first action needing two undos. 

I'll look into that fix logic again, rejoining resets textId is unavoidable I think (unless want to keep it as state in Hub, then tell it to Story student on join), but the next page behavior above should be attemped a fix? wdyt

**Comment by nicolauscg** [comment]
okay so the sole purpose of reseting textId to 1 was to safeguard conditional below so it only runs after student has placed a text, we could replicate this by having a boolean state `hasPlacedNewTextThisPage` which is set to false on every page and set to true on `interactCanvas` func, in the else block where u the have comment `insert new text`

```
useEffect(() => {
  if (editingTextId === 0 && somethingToMakeThisOnlyRunAfterUserPlacedAText) {
    placeCheckpoint(ToolMode.Text);
  }
}, [editingTextId, hasPlacedNewTextThisPage, placeCheckpoint]);
```

**Review by nicolauscg — APPROVED** [review]

**Pull request merged**
