### PR TITLE
[FAB-133] HiFi Canvas Tutorial

### PR DESCRIPTION
**Pull request by nicolauscg**
features

- [x] tutorial for canvas drawing screen, steps includes:
  - mention of tutorial button in navbar to access it again
  - drawing follows theme and student is assigned a specific role (chip row above canvas)
  - can only see own drawing, to view combined drawing, see hub screen
  - explain each tool available to story and drawing roles
- [x] remember when tutorial is accessed and do not automatically show prompt again for 1 day
- [x] hide login, register, profile, logout button for student pages i.e. when url is `/join`
- [x] fableous logo in navbar not clickable when student on drawing session

bugs found

- on short screens, when canvas toolbar y-axis overflows to scroll, its scroll position does not align when tutorial is explaining the brush tool
  - tried all props related to scroll and does not seem to change any behavior, so since this is a minor bug only present on small screens, can consider leaving it
- [x] manually starting tutorial through navbar button shows first step of tutorial, which is asking "do you want to go through the tutorial?", its kinda akward
- [x] tutorial step with `center` placement causes scrollbar to appear on canvas drawing screen

out of scope
- matching UI of tooltip to prototype, could be taken by Will for his gallery tutorial task
- review and finalising tutorial steps, wording

### CODE REVIEW

**Comment by daystram** [comment]
We could also hide the profile and logout button, and disable the Fableous logo button when the user is in the canvas page.

**Comment by nicolauscg** [comment]
> We could also hide the profile and logout button, and disable the Fableous logo button when the user is in the canvas page.

good idea, at the moment I only hid login register buttons, will do the rest in a moment

**Comment by daystram** [comment]
This is also an apparent bug, viewport scrolls when tooltip appears
ss

**Comment by nicolauscg** [comment]
previous two comments by Dan have been addressed

**Comment by daystram** [comment]
Rename `localStorage.ts` to `storage.ts`?

**Comment by daystram** [comment]
For the IDs in `tutorialTargetIds.ts`, how about making them all enums?

**Comment by daystram** [comment]
Other than that, all G

**Comment by daystram** [comment]
I can't figure out why the spotlight on the eraser button has no padding while the other has.
image
image

**Comment by daystram** [comment]
I wonder if the transition animation could be made less jerky than this

https://user-images.githubusercontent.com/21298332/135761023-c6dd883d-2fef-4ac4-80d2-01ac4034663d.mov

**Comment by daystram** [comment]
The tutorial should also be cancelled when the page state changes. Currently, if the drawing finishes or resets back to the form page, the tutorial overlay remains

**Comment by nicolauscg** [comment]
- renamed `localStorage.ts` to `storage.ts`, function names are still kept the same
- combined ids to one enum in `tutorialTargetIds.ts`
- fixed eraser icon to have same size with the rest, the inconsistency before was because there is no eraser icon in material ui, so I used one found on the internet
- disabled animation for tutorial tooltip, yes it does look weird
- tutorial will correctly close when controllerState changes

**Review by daystram — APPROVED** [review]

**Review by daystram — APPROVED** [review]

**Pull request merged**
